apiVersion: apps/v1
kind: Deployment
metadata:
  name: appvote
  labels:
    app: appvotetag
spec:
  selector:
    matchLabels:
      app: appvotetag
  replicas: 1
  template:
    metadata:
      labels:
        app: appvotetag
    spec:
      containers:
      - name: appvote
        image: whujin11e/public:azure_voting_app
        ports:
        - containerPort: 80
        env:
        # - name: REDIS
        #   value: "rediscluster"
        - name: STRESS_SECS
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: lbappvote
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: appvotetag