apiVersion: apps/v1
kind: Deployment
metadata:
  name: appvote
  labels:
    app: appvotetag
spec:
  selector:
    matchLabels:
      app: appvotetag
  replicas: 1
  template:
    metadata:
      labels:
        app: appvotetag
    spec:
      containers:
      - name: appvote
        image: whujin11e/public:azure_voting_app
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "rediscluster"
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
              name: redis
              key: REDIS_PWD
        - name: STRESS_SECS
          value: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: appvotetag
spec:
  selector:
    app: appvotetag
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appvotetag
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: appvotetag
            port:
              number: 80
        pathType: Exact