apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redistag
spec:
  selector:
    matchLabels:
      app: redistag
  replicas: 1
  template:
    metadata:
      labels:
        app: redistag
    spec:
      containers:
      - name: redis
        image: redis
        args: ["--requirepass", "$(REDIS_PASS)"]
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: rediscluster
spec:
  type: ClusterIP
  ports:
  - port: 6379
  selector:
    app: redistag